version: '3.8'

volumes:
  local_db_data: {}

services:
  db:
    build:
      context: .
      dockerfile: compose/db/Dockerfile
    container_name: booking_db
    env_file:
      - ./compose/envs/db.env
    volumes:
      - local_db_data:/var/lib/mysql
    ports:
      - "33061:3306"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: compose/api/Dockerfile
    container_name: booking_api
    env_file:
      - ./compose/envs/db.env
      - ./compose/envs/api.env
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    command: /start
